spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:properties/,classpath:properties/provider-model/,
          #username:
          #password:
          #search-paths: test-CONFIG
  application:
    name: config-server
  profiles:
    active: native
#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

server:
    port: 7006



